name: Improve Commits with OpenCommit

on:
  push:
    branches:
      - main

jobs:
  opencommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: OpenCommit — improve commits with AI 🧙
        uses: di-sukharev/opencommit@github-action-v1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
